version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
# docker-compose up -d
# docker-compose down

# Connection string example:
# postgres://<username>:<password>@<host>:<port>/<database>
# For this setup:
# postgres://postgres:pgsanuar@db:5432/messages
